AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ProcessDeploymentRecords:
    Properties:
      CodeUri: s3://us-east-1-blox-scheduler-manager/366d7357ac2072c562574e01c4888964
      Events:
        DeploymentRecordEvent:
          Properties:
            BatchSize: 10
            StartingPosition: TRIM_HORIZON
            Stream: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Deployments/stream/2017-08-23T00:09:35.158
          Type: DynamoDB
      Handler: com.amazonaws.blox.schedulingmanager.stream.processor.StreamProcessorHandler
      MemorySize: 256
      Policies:
      - Statement:
        - Action:
          - dynamodb:DescribeStream
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
          Effect: Allow
          Resource: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Deployments/stream/*
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Effect: Allow
          Resource: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
        Version: '2012-10-17'
      Runtime: java8
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
